### ISSUE TITLE
Sugestão: MVC

### ISSUE THREAD

**Issue by joaocanuto** [caio11pessoa/GerenciadorDeTarefasCLI#10]
https://github.com/caio11pessoa/GerenciadorDeTarefasCLI/blob/6ac425b97a165247833ca2faae1591db7aa0e898/GerenciadorDeTarefas/main.swift#L13

Acredito que seja importante considerar a comunicação entre a view e o controller no contexto do MVC. Talvez seja mais apropriado que a tela inicializadora esteja dentro da classe da view, já que uma view fora do controller ou sem comunicação pode não fazer sentido dentro do MVC.

**Comment by IanPacini123** [comment]
Ficou assim por que foi feito de ultima hora, obrigado por lembrar, realmente não era pra existir essa linha na main.
