### ISSUE TITLE
Sugestão: Controlar a quantidade de caracteres dentro da controller.

### ISSUE THREAD

**Issue by joaocanuto** [caio11pessoa/GerenciadorDeTarefasCLI#8]
https://github.com/caio11pessoa/GerenciadorDeTarefasCLI/blob/6ac425b97a165247833ca2faae1591db7aa0e898/GerenciadorDeTarefas/AtividadeController.swift#L64
Pelo que sugere na view, ele diz que o máximo é 33 caracteres para o titulo, e 100 caracteres para descrição, poderia ter essa validação dentro da controller.

_Ademais, Ficou muito bom o código! Muito bem estruturado e me inspirou para novas ideias no meu! Parabéns amigos!_

**Comment by IanPacini123** [comment]
Decidimos nao 'travar' o usuario caso ele ponha um nome maior que o esperado, como se ve em apps de celular(que são mais dinâmicos ent nn sofrem tanto com isso).
Ademais, obrigado amigo!
