### ISSUE TITLE
uppercased/lowercased

### ISSUE THREAD

**Issue by GabrielCarvalhoM** [caio11pessoa/GerenciadorDeTarefasCLI#9]
Nos cases, poderia ter usado .uppercased ou .lowercased ao invés de criar os casos verificando a letra minúscula e depois maiúscula, tratando diretamente no input do usuário.

**Comment by IanPacini123** [comment]
Olá, segundo nossos testes de desempenho (Simplesmente iterar sobre um teste entre as 2 opções e um formatar antes de testar cerca de 100M de vezes), o método utilizado no código é mais eficiente, isso provavelmente se da pq pra transformar de lower pra upper ele tem que transformar pela tabela ascii, o que adiciona um processamento na função.
